# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_gbvi', [dirname(__file__)])
        except ImportError:
            import _gbvi
            return _gbvi
        if fp is not None:
            try:
                _mod = imp.load_module('_gbvi', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _gbvi = swig_import_helper()
    del swig_import_helper
else:
    import _gbvi
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _gbvi.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _gbvi.SwigPyIterator_value(self)
    def incr(self, n=1): return _gbvi.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _gbvi.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _gbvi.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _gbvi.SwigPyIterator_equal(self, *args)
    def copy(self): return _gbvi.SwigPyIterator_copy(self)
    def next(self): return _gbvi.SwigPyIterator_next(self)
    def __next__(self): return _gbvi.SwigPyIterator___next__(self)
    def previous(self): return _gbvi.SwigPyIterator_previous(self)
    def advance(self, *args): return _gbvi.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _gbvi.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _gbvi.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _gbvi.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _gbvi.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _gbvi.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _gbvi.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _gbvi.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectord(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectord, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectord, name)
    __repr__ = _swig_repr
    def iterator(self): return _gbvi.vectord_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _gbvi.vectord___nonzero__(self)
    def __bool__(self): return _gbvi.vectord___bool__(self)
    def __len__(self): return _gbvi.vectord___len__(self)
    def pop(self): return _gbvi.vectord_pop(self)
    def __getslice__(self, *args): return _gbvi.vectord___getslice__(self, *args)
    def __setslice__(self, *args): return _gbvi.vectord___setslice__(self, *args)
    def __delslice__(self, *args): return _gbvi.vectord___delslice__(self, *args)
    def __delitem__(self, *args): return _gbvi.vectord___delitem__(self, *args)
    def __getitem__(self, *args): return _gbvi.vectord___getitem__(self, *args)
    def __setitem__(self, *args): return _gbvi.vectord___setitem__(self, *args)
    def append(self, *args): return _gbvi.vectord_append(self, *args)
    def empty(self): return _gbvi.vectord_empty(self)
    def size(self): return _gbvi.vectord_size(self)
    def clear(self): return _gbvi.vectord_clear(self)
    def swap(self, *args): return _gbvi.vectord_swap(self, *args)
    def get_allocator(self): return _gbvi.vectord_get_allocator(self)
    def begin(self): return _gbvi.vectord_begin(self)
    def end(self): return _gbvi.vectord_end(self)
    def rbegin(self): return _gbvi.vectord_rbegin(self)
    def rend(self): return _gbvi.vectord_rend(self)
    def pop_back(self): return _gbvi.vectord_pop_back(self)
    def erase(self, *args): return _gbvi.vectord_erase(self, *args)
    def __init__(self, *args): 
        this = _gbvi.new_vectord(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _gbvi.vectord_push_back(self, *args)
    def front(self): return _gbvi.vectord_front(self)
    def back(self): return _gbvi.vectord_back(self)
    def assign(self, *args): return _gbvi.vectord_assign(self, *args)
    def resize(self, *args): return _gbvi.vectord_resize(self, *args)
    def insert(self, *args): return _gbvi.vectord_insert(self, *args)
    def reserve(self, *args): return _gbvi.vectord_reserve(self, *args)
    def capacity(self): return _gbvi.vectord_capacity(self)
    __swig_destroy__ = _gbvi.delete_vectord
    __del__ = lambda self : None;
vectord_swigregister = _gbvi.vectord_swigregister
vectord_swigregister(vectord)

class vectorddd(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorddd, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorddd, name)
    __repr__ = _swig_repr
    def iterator(self): return _gbvi.vectorddd_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _gbvi.vectorddd___nonzero__(self)
    def __bool__(self): return _gbvi.vectorddd___bool__(self)
    def __len__(self): return _gbvi.vectorddd___len__(self)
    def pop(self): return _gbvi.vectorddd_pop(self)
    def __getslice__(self, *args): return _gbvi.vectorddd___getslice__(self, *args)
    def __setslice__(self, *args): return _gbvi.vectorddd___setslice__(self, *args)
    def __delslice__(self, *args): return _gbvi.vectorddd___delslice__(self, *args)
    def __delitem__(self, *args): return _gbvi.vectorddd___delitem__(self, *args)
    def __getitem__(self, *args): return _gbvi.vectorddd___getitem__(self, *args)
    def __setitem__(self, *args): return _gbvi.vectorddd___setitem__(self, *args)
    def append(self, *args): return _gbvi.vectorddd_append(self, *args)
    def empty(self): return _gbvi.vectorddd_empty(self)
    def size(self): return _gbvi.vectorddd_size(self)
    def clear(self): return _gbvi.vectorddd_clear(self)
    def swap(self, *args): return _gbvi.vectorddd_swap(self, *args)
    def get_allocator(self): return _gbvi.vectorddd_get_allocator(self)
    def begin(self): return _gbvi.vectorddd_begin(self)
    def end(self): return _gbvi.vectorddd_end(self)
    def rbegin(self): return _gbvi.vectorddd_rbegin(self)
    def rend(self): return _gbvi.vectorddd_rend(self)
    def pop_back(self): return _gbvi.vectorddd_pop_back(self)
    def erase(self, *args): return _gbvi.vectorddd_erase(self, *args)
    def __init__(self, *args): 
        this = _gbvi.new_vectorddd(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _gbvi.vectorddd_push_back(self, *args)
    def front(self): return _gbvi.vectorddd_front(self)
    def back(self): return _gbvi.vectorddd_back(self)
    def assign(self, *args): return _gbvi.vectorddd_assign(self, *args)
    def resize(self, *args): return _gbvi.vectorddd_resize(self, *args)
    def insert(self, *args): return _gbvi.vectorddd_insert(self, *args)
    def reserve(self, *args): return _gbvi.vectorddd_reserve(self, *args)
    def capacity(self): return _gbvi.vectorddd_capacity(self)
    __swig_destroy__ = _gbvi.delete_vectorddd
    __del__ = lambda self : None;
vectorddd_swigregister = _gbvi.vectorddd_swigregister
vectorddd_swigregister(vectorddd)

class vectori(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectori, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectori, name)
    __repr__ = _swig_repr
    def iterator(self): return _gbvi.vectori_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _gbvi.vectori___nonzero__(self)
    def __bool__(self): return _gbvi.vectori___bool__(self)
    def __len__(self): return _gbvi.vectori___len__(self)
    def pop(self): return _gbvi.vectori_pop(self)
    def __getslice__(self, *args): return _gbvi.vectori___getslice__(self, *args)
    def __setslice__(self, *args): return _gbvi.vectori___setslice__(self, *args)
    def __delslice__(self, *args): return _gbvi.vectori___delslice__(self, *args)
    def __delitem__(self, *args): return _gbvi.vectori___delitem__(self, *args)
    def __getitem__(self, *args): return _gbvi.vectori___getitem__(self, *args)
    def __setitem__(self, *args): return _gbvi.vectori___setitem__(self, *args)
    def append(self, *args): return _gbvi.vectori_append(self, *args)
    def empty(self): return _gbvi.vectori_empty(self)
    def size(self): return _gbvi.vectori_size(self)
    def clear(self): return _gbvi.vectori_clear(self)
    def swap(self, *args): return _gbvi.vectori_swap(self, *args)
    def get_allocator(self): return _gbvi.vectori_get_allocator(self)
    def begin(self): return _gbvi.vectori_begin(self)
    def end(self): return _gbvi.vectori_end(self)
    def rbegin(self): return _gbvi.vectori_rbegin(self)
    def rend(self): return _gbvi.vectori_rend(self)
    def pop_back(self): return _gbvi.vectori_pop_back(self)
    def erase(self, *args): return _gbvi.vectori_erase(self, *args)
    def __init__(self, *args): 
        this = _gbvi.new_vectori(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _gbvi.vectori_push_back(self, *args)
    def front(self): return _gbvi.vectori_front(self)
    def back(self): return _gbvi.vectori_back(self)
    def assign(self, *args): return _gbvi.vectori_assign(self, *args)
    def resize(self, *args): return _gbvi.vectori_resize(self, *args)
    def insert(self, *args): return _gbvi.vectori_insert(self, *args)
    def reserve(self, *args): return _gbvi.vectori_reserve(self, *args)
    def capacity(self): return _gbvi.vectori_capacity(self)
    __swig_destroy__ = _gbvi.delete_vectori
    __del__ = lambda self : None;
vectori_swigregister = _gbvi.vectori_swigregister
vectori_swigregister(vectori)

class vectorii(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorii, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorii, name)
    __repr__ = _swig_repr
    def iterator(self): return _gbvi.vectorii_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _gbvi.vectorii___nonzero__(self)
    def __bool__(self): return _gbvi.vectorii___bool__(self)
    def __len__(self): return _gbvi.vectorii___len__(self)
    def pop(self): return _gbvi.vectorii_pop(self)
    def __getslice__(self, *args): return _gbvi.vectorii___getslice__(self, *args)
    def __setslice__(self, *args): return _gbvi.vectorii___setslice__(self, *args)
    def __delslice__(self, *args): return _gbvi.vectorii___delslice__(self, *args)
    def __delitem__(self, *args): return _gbvi.vectorii___delitem__(self, *args)
    def __getitem__(self, *args): return _gbvi.vectorii___getitem__(self, *args)
    def __setitem__(self, *args): return _gbvi.vectorii___setitem__(self, *args)
    def append(self, *args): return _gbvi.vectorii_append(self, *args)
    def empty(self): return _gbvi.vectorii_empty(self)
    def size(self): return _gbvi.vectorii_size(self)
    def clear(self): return _gbvi.vectorii_clear(self)
    def swap(self, *args): return _gbvi.vectorii_swap(self, *args)
    def get_allocator(self): return _gbvi.vectorii_get_allocator(self)
    def begin(self): return _gbvi.vectorii_begin(self)
    def end(self): return _gbvi.vectorii_end(self)
    def rbegin(self): return _gbvi.vectorii_rbegin(self)
    def rend(self): return _gbvi.vectorii_rend(self)
    def pop_back(self): return _gbvi.vectorii_pop_back(self)
    def erase(self, *args): return _gbvi.vectorii_erase(self, *args)
    def __init__(self, *args): 
        this = _gbvi.new_vectorii(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _gbvi.vectorii_push_back(self, *args)
    def front(self): return _gbvi.vectorii_front(self)
    def back(self): return _gbvi.vectorii_back(self)
    def assign(self, *args): return _gbvi.vectorii_assign(self, *args)
    def resize(self, *args): return _gbvi.vectorii_resize(self, *args)
    def insert(self, *args): return _gbvi.vectorii_insert(self, *args)
    def reserve(self, *args): return _gbvi.vectorii_reserve(self, *args)
    def capacity(self): return _gbvi.vectorii_capacity(self)
    __swig_destroy__ = _gbvi.delete_vectorii
    __del__ = lambda self : None;
vectorii_swigregister = _gbvi.vectorii_swigregister
vectorii_swigregister(vectorii)

class vectorstring(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorstring, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorstring, name)
    __repr__ = _swig_repr
    def iterator(self): return _gbvi.vectorstring_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _gbvi.vectorstring___nonzero__(self)
    def __bool__(self): return _gbvi.vectorstring___bool__(self)
    def __len__(self): return _gbvi.vectorstring___len__(self)
    def pop(self): return _gbvi.vectorstring_pop(self)
    def __getslice__(self, *args): return _gbvi.vectorstring___getslice__(self, *args)
    def __setslice__(self, *args): return _gbvi.vectorstring___setslice__(self, *args)
    def __delslice__(self, *args): return _gbvi.vectorstring___delslice__(self, *args)
    def __delitem__(self, *args): return _gbvi.vectorstring___delitem__(self, *args)
    def __getitem__(self, *args): return _gbvi.vectorstring___getitem__(self, *args)
    def __setitem__(self, *args): return _gbvi.vectorstring___setitem__(self, *args)
    def append(self, *args): return _gbvi.vectorstring_append(self, *args)
    def empty(self): return _gbvi.vectorstring_empty(self)
    def size(self): return _gbvi.vectorstring_size(self)
    def clear(self): return _gbvi.vectorstring_clear(self)
    def swap(self, *args): return _gbvi.vectorstring_swap(self, *args)
    def get_allocator(self): return _gbvi.vectorstring_get_allocator(self)
    def begin(self): return _gbvi.vectorstring_begin(self)
    def end(self): return _gbvi.vectorstring_end(self)
    def rbegin(self): return _gbvi.vectorstring_rbegin(self)
    def rend(self): return _gbvi.vectorstring_rend(self)
    def pop_back(self): return _gbvi.vectorstring_pop_back(self)
    def erase(self, *args): return _gbvi.vectorstring_erase(self, *args)
    def __init__(self, *args): 
        this = _gbvi.new_vectorstring(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _gbvi.vectorstring_push_back(self, *args)
    def front(self): return _gbvi.vectorstring_front(self)
    def back(self): return _gbvi.vectorstring_back(self)
    def assign(self, *args): return _gbvi.vectorstring_assign(self, *args)
    def resize(self, *args): return _gbvi.vectorstring_resize(self, *args)
    def insert(self, *args): return _gbvi.vectorstring_insert(self, *args)
    def reserve(self, *args): return _gbvi.vectorstring_reserve(self, *args)
    def capacity(self): return _gbvi.vectorstring_capacity(self)
    __swig_destroy__ = _gbvi.delete_vectorstring
    __del__ = lambda self : None;
vectorstring_swigregister = _gbvi.vectorstring_swigregister
vectorstring_swigregister(vectorstring)


def addMolecules(*args):
  return _gbvi.addMolecules(*args)
addMolecules = _gbvi.addMolecules

def getGBVIEnergyFromFile(*args):
  return _gbvi.getGBVIEnergyFromFile(*args)
getGBVIEnergyFromFile = _gbvi.getGBVIEnergyFromFile

def getGBVIEnergy(*args):
  return _gbvi.getGBVIEnergy(*args)
getGBVIEnergy = _gbvi.getGBVIEnergy
# This file is compatible with both classic and new-style classes.


